### ISSUE TITLE
fix typos/style on Tour of the Discovery Environment tour

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [CyVerse-learning-materials/cyverse_mooc#10]
question bar - should be "question button"
Datastore - should be "Data Store"

Also, 
Search bar should mention a dropdown menu to specifically search a catagory (i.e. apps, data)

**Comment by KristerJazz** [comment]
Hi @JasonJWilliamsNY, I already fixed this. Feel free to comment if needed.
