### ISSUE TITLE
Tour of the Discovery Environment try it and questions

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [CyVerse-learning-materials/cyverse_mooc#11]
- Try it asks users to create a folder, is this covered in the video? If not, can there be a little more help 
- Although videos are not a DE menu (assessment question 1) can we mention that help videos and webinars are available in the dashboard? 
- Both questions need question marks

**Comment by KristerJazz** [comment]
Yes. It is covered on the video based on our story board.

Fixed according to your suggestions.

d0767d4cb9cfaa18ae6a37c8c0b74b1ea5f523fd
737c5e43b80bec21b2ce9b1ef909a78c609de836
