### ISSUE TITLE
Data Management I redundant instruction

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [CyVerse-learning-materials/cyverse_mooc#12]
Downloading data instruction 4 is redundant with instruction 3, once they choose community data from the drop down, they will be in that location. Also Number 4 should be written for people who will be clicking through the folders (i.e. scroll down to find "cyverse_training", next click on the ..." . You could also mention pasting the exact path as well.

**Comment by MCMaurer** [comment]
Good find, I clarified these directions.
