### ISSUE TITLE
FAIR and Data Management I

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [CyVerse-learning-materials/cyverse_mooc#2]
Is there going to be a video and discussion of FAIR? Should we have a subheading for that?

**Comment by MCMaurer** [comment]
The video primarily covers FAIR data, but I thought the webpage was supposed to essentially just hold the instructions for each activity, whereas the video + slides provide the instructional content. Should I add all the information from the slides into the page for Data Management I?

**Comment by JasonJWilliamsNY** [comment]
No worries, as long as it's tied in that way!
